/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/reports/v0-nsfw/reports/gross-transactions": {
    /** Returns a list of gross transactions with metadata (folio and reservation details).<br>You must have this scope: 'reports.read'. */
    post: operations["ReportsReportsGross-transactionsPost"];
  };
  "/reports/v0-nsfw/reports/ordered-services": {
    /** Returns a list of ordered services per day with information about the guest and the reservation this service was ordered for.<br>You must have this scope: 'reports.read'. */
    get: operations["ReportsReportsOrdered-servicesGet"];
  };
  "/reports/v0-nsfw/reports/room-nights-consumed": {
    /**
     * Returns room nights for a property for a certain month. Only over-night rateplans are considered.
     * <br />
     * DEPRECATED: will be replaced by "/room-nights"<br>You must have this scope: 'reports.read'.
     */
    get: operations["ReportsReportsRoom-nights-consumedGet"];
  };
  "/reports/v0-nsfw/reports/room-nights": {
    /**
     * Returns room nights for a property for a certain month. Only over-night rateplans are considered.<br />
     * Includes statistical information on purpose of travel, and nationality.
     * The status considered are: in-house, confirmed, and checked out.<br>You must have this scope: 'reports.read'.
     */
    get: operations["ReportsReportsRoom-nightsGet"];
  };
  "/reports/v0-nsfw/reports/bed-nights": {
    /**
     * Returns bed nights for a property for a certain month. Only over-night rateplans are considered.<br />
     * Counts number of guests.
     * Includes statistical information on purpose of travel, and nationality. The data is taken from the primary guest only.
     * The status considered are: in-house, confirmed, and checked out.<br>You must have this scope: 'reports.read'.
     */
    get: operations["ReportsReportsBed-nightsGet"];
  };
  "/reports/v0-nsfw/reports/arrivals": {
    /**
     * Returns number of arriving guests for a property for a certain month. Only over-night rateplans are considered.<br />
     * Includes statistical information on purpose of travel, and nationality. The data is taken from the primary guest only.
     * The status considered are: in-house, confirmed, and checked out.<br>You must have this scope: 'reports.read'.
     */
    get: operations["ReportsReportsArrivalsGet"];
  };
  "/reports/v0-nsfw/reports/property-performance": {
    /**
     * The property performance API return you key performance indicator for the selected property like occupancy, ADR and RevPAR.
     * It only considers the originally booked amounts for sold units excluding any additional services or manually posted charges
     * or allowances. The results can be filterd to only show you data for a certain part of the business. For example you can exclude
     * day-use reservations or complimentary rate plans.<br>You must have this scope: 'reports.read'.
     */
    get: operations["ReportsReportsProperty-performanceGet"];
  };
  "/reports/v0-nsfw/reports/company-invoices-vat": {
    /** <br>You must have this scope: 'reports.read'. */
    get: operations["ReportsReportsCompany-invoices-vatGet"];
  };
  "/reports/v0-nsfw/reports/revenues": {
    /** <br>You must have this scope: 'reports.read'. */
    get: operations["ReportsReportsRevenuesGet"];
  };
}

export interface definitions {
  AddressModel: {
    addressLine1: string;
    addressLine2?: string;
    postalCode: string;
    city: string;
    regionCode?: string;
    countryCode: string;
  };
  CompaniesVatReportItemModel: {
    company: definitions["CompanyModel"];
    invoice: definitions["InvoiceModel"];
  };
  /**
   * @example {
   *   "companyInvoices": [
   *     {
   *       "company": {
   *         "id": "MUC-APALEO",
   *         "code": "APALEO",
   *         "name": "APALEO Company",
   *         "taxId": "DE311046461",
   *         "address": {
   *           "addressLine1": "Dachauerstr. 15 A",
   *           "postalCode": "80335",
   *           "city": "Munich",
   *           "countryCode": "DE"
   *         }
   *       },
   *       "invoice": {
   *         "number": "2019050000009",
   *         "date": "2024-03-12",
   *         "subTotal": {
   *           "amount": 114.0,
   *           "currency": "EUR"
   *         },
   *         "outstandingPayment": {
   *           "amount": 50.0,
   *           "currency": "EUR"
   *         },
   *         "taxDetails": [
   *           {
   *             "vatType": "Reduced",
   *             "vatPercent": 14.0,
   *             "net": {
   *               "amount": 100.0,
   *               "currency": "EUR"
   *             },
   *             "tax": {
   *               "amount": 14.0,
   *               "currency": "EUR"
   *             }
   *           }
   *         ]
   *       }
   *     }
   *   ],
   *   "count": 1
   * }
   */
  CompaniesVatReportListModel: {
    /** @description List of company invoices */
    companyInvoices: definitions["CompaniesVatReportItemModel"][];
    /**
     * Format: int64
     * @description Total count of items
     */
    count: number;
  };
  CompanyModel: {
    /** @description The ID of the company */
    id: string;
    /** @description The code for the company */
    code: string;
    /** @description The name of the company */
    name: string;
    /** @description The tax ID of the company */
    taxId?: string;
    address: definitions["AddressModel"];
  };
  CountryEntry: {
    /** @description 2 letter ISO country code */
    countryCode?: string;
    /** Format: int32 */
    number: number;
    /** Format: double */
    percent: number;
    reservationIds?: string[];
  };
  EmbeddedUnitGroupModel: {
    /** @description The unit group id */
    id: string;
    /** @description The code for the unit group that can be shown in reports and table views */
    code?: string;
    /** @description The name for the unit group */
    name?: string;
    /** @description The description for the unit group */
    description?: string;
    /** @description The unit group type */
    type?: "BedRoom" | "MeetingRoom" | "EventSpace" | "ParkingLot" | "Other";
  };
  ExportAccountModel: {
    /** @description The account name */
    name: string;
    /** @description The account number */
    number: string;
    /** @description The number of the parent account */
    parentNumber?: string;
    /** @description The account type */
    type:
      | "Revenues"
      | "Payments"
      | "Liabilities"
      | "Receivables"
      | "Vat"
      | "House"
      | "AccountsReceivable"
      | "CityTaxes"
      | "TransitoryItems"
      | "VatOnLiabilities"
      | "LossOfAccountsReceivable"
      | "SecondCityTax";
  };
  /**
   * @example {
   *   "total": 279,
   *   "travelPurposeBreakdown": [
   *     {
   *       "purpose": "Leisure",
   *       "number": 274,
   *       "percent": 98.20,
   *       "reservationIds": [
   *         "AHSJFHSH-1",
   *         "HFNDHSKA-2"
   *       ]
   *     },
   *     {
   *       "purpose": "Business",
   *       "number": 2,
   *       "percent": 0.72,
   *       "reservationIds": [
   *         "AHSJFHSH-1",
   *         "HFNDHSKA-2"
   *       ]
   *     },
   *     {
   *       "number": 2,
   *       "percent": 0.72,
   *       "reservationIds": [
   *         "AHSJFHSH-1",
   *         "HFNDHSKA-2"
   *       ]
   *     }
   *   ],
   *   "nationalityBreakdown": [
   *     {
   *       "countryCode": "DE",
   *       "number": 118,
   *       "percent": 42.29,
   *       "reservationIds": [
   *         "AHSJFHSH-1",
   *         "HFNDHSKA-2"
   *       ]
   *     },
   *     {
   *       "countryCode": "GB",
   *       "number": 18,
   *       "percent": 6.45,
   *       "reservationIds": [
   *         "AHSJFHSH-1",
   *         "HFNDHSKA-2"
   *       ]
   *     },
   *     {
   *       "number": 143,
   *       "percent": 51.26,
   *       "reservationIds": [
   *         "AHSJFHSH-1",
   *         "HFNDHSKA-2"
   *       ]
   *     }
   *   ],
   *   "countryOfResidenceBreakdown": [
   *     {
   *       "countryCode": "DE",
   *       "number": 132,
   *       "percent": 47.31,
   *       "reservationIds": [
   *         "AHSJFHSH-1",
   *         "HFNDHSKA-2"
   *       ]
   *     },
   *     {
   *       "countryCode": "GB",
   *       "number": 9,
   *       "percent": 3.23,
   *       "reservationIds": [
   *         "AHSJFHSH-1",
   *         "HFNDHSKA-2"
   *       ]
   *     },
   *     {
   *       "number": 138,
   *       "percent": 49.46,
   *       "reservationIds": [
   *         "AHSJFHSH-1",
   *         "HFNDHSKA-2"
   *       ]
   *     }
   *   ]
   * }
   */
  GuestReportModel: {
    /**
     * Format: int32
     * @description Total number for all guests.
     */
    total: number;
    /** @description Breakdown by travel purpose. */
    travelPurposeBreakdown?: definitions["TravelPurposeEntry"][];
    /** @description Breakdown by nationality. */
    nationalityBreakdown?: definitions["CountryEntry"][];
    /** @description Breakdown by country of residence. */
    countryOfResidenceBreakdown?: definitions["CountryEntry"][];
  };
  InvoiceModel: {
    /** @description Invoice number */
    number?: string;
    /**
     * Format: date
     * @description Date the invoice has been created
     * @example 2020-10-10
     */
    date: string;
    subTotal: definitions["MonetaryValueModel"];
    outstandingPayment?: definitions["MonetaryValueModel"];
    /** @description The subtotal, displaying net and tax amount for each VAT type */
    taxDetails?: definitions["TaxDetailModel"][];
  };
  MessageItemCollection: {
    messages?: string[];
  };
  MonetaryValueModel: {
    /** Format: double */
    amount: number;
    currency: string;
  };
  OrderedServicesGuestModel: {
    /** @description Title of the guest */
    title?: "Mr" | "Ms" | "Dr" | "Prof" | "Mrs" | "Other";
    /** @description Gender of the guest */
    gender?: "Female" | "Male" | "Other";
    /** @description First name of the guest */
    firstName?: string;
    /** @description Middle initial of the guest */
    middleInitial?: string;
    /** @description Last name of the guest */
    lastName: string;
  };
  OrderedServicesItemModel: {
    /** @description The service id */
    id: string;
    /** @description The code for the service */
    code: string;
    /** @description The name for the service */
    name: string;
    /**
     * Format: date
     * @description The date this service is delivered
     * @example 2020-10-10
     */
    serviceDate: string;
    /**
     * Format: int32
     * @description The count of services ordered
     */
    count: number;
    guest?: definitions["OrderedServicesGuestModel"];
    reservation: definitions["OrderedServicesReservationModel"];
    unit?: definitions["OrderedServicesUnitModel"];
    unitGroup: definitions["OrderedServicesUnitGroupModel"];
  };
  /**
   * @example {
   *   "orderedServices": [
   *     {
   *       "id": "MUC-BRK",
   *       "code": "BRK",
   *       "name": "Breakfast",
   *       "serviceDate": "2024-03-09",
   *       "count": 1,
   *       "guest": {
   *         "title": "Mr",
   *         "gender": "Male",
   *         "firstName": "John",
   *         "middleInitial": "G.",
   *         "lastName": "Doe"
   *       },
   *       "reservation": {
   *         "id": "XPGMSXGF-1",
   *         "arrival": "2024-03-08T17:00:00+01:00",
   *         "departure": "2024-03-10T17:00:00+01:00",
   *         "persons": 2
   *       },
   *       "unit": {
   *         "id": "HDHD",
   *         "name": "A.001"
   *       },
   *       "unitGroup": {
   *         "id": "MUC-SGL",
   *         "code": "SGL",
   *         "name": "Single room"
   *       }
   *     }
   *   ],
   *   "count": 1
   * }
   */
  OrderedServicesListModel: {
    /** @description List of ordered services */
    orderedServices: definitions["OrderedServicesItemModel"][];
    /**
     * Format: int64
     * @description Total count of items
     */
    count: number;
  };
  OrderedServicesReservationModel: {
    /** @description Reservation id */
    id: string;
    /**
     * Format: date-time
     * @description Date of arrival<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>
     */
    arrival: string;
    /**
     * Format: date-time
     * @description Date of departure<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>
     */
    departure: string;
    /**
     * Format: int32
     * @description Number of persons
     */
    persons: number;
  };
  OrderedServicesUnitGroupModel: {
    /** @description The unit group id */
    id: string;
    /** @description The code for the unit group */
    code: string;
    /** @description The name for the unit group */
    name: string;
  };
  OrderedServicesUnitModel: {
    /** @description The unit id */
    id: string;
    /** @description The name for the unit */
    name: string;
  };
  PropertyPerformancePerUnitGroupModel: {
    unitGroup: definitions["EmbeddedUnitGroupModel"];
    /**
     * Format: int32
     * @description The number of units physically existing excluding the ones which are out of inventory
     */
    houseCount: number;
    /**
     * Format: int32
     * @description The number of items (e.g. beds, seats, etc.) physically existing excluding the ones which are out of inventory
     */
    houseItemsCount: number;
    /**
     * Format: int32
     * @description The number of sold units plus definitely blocked units from group bookings
     */
    soldCount: number;
    /**
     * Format: int32
     * @description The number of sold items (e.g. beds, seats, etc.) plus definitely blocked items from group bookings
     */
    soldItemsCount: number;
    /**
     * Format: int32
     * @description The number of unsold units: house count minus sold units and out of order units
     */
    unsoldCount: number;
    /**
     * Format: int32
     * @description The number of unsold items (e.g. beds, seats, etc.): house items count minus sold items and out of order items
     */
    unsoldItemsCount: number;
    /**
     * Format: int32
     * @description The number of units which are out of order
     */
    outOfOrderCount: number;
    /**
     * Format: int32
     * @description The number of items (e.g. beds, seats, etc.) which are out of order
     */
    outOfOrderItemsCount: number;
    /**
     * Format: int32
     * @description The number of units which are tentatively blocked
     */
    tentativelyBlockedCount: number;
    /**
     * Format: int32
     * @description The number of items (beds, seats, etc.) which are tentatively blocked
     */
    tentativelyBlockedItemsCount: number;
    /**
     * Format: int32
     * @description The number of arrivals units
     */
    arrivalsCount: number;
    /**
     * Format: int32
     * @description The number of departures units
     */
    departuresCount: number;
    /**
     * Format: int32
     * @description The number of no-show units
     */
    noShowsCount: number;
    /**
     * Format: int32
     * @description The number of cancelled units
     */
    cancellationsCount: number;
    /**
     * Format: double
     * @description The occupancy in percent, which is the ratio of sold units in relation to house count minus out of order units
     */
    occupancyPercentage: number;
    grossUnitRevenue: definitions["MonetaryValueModel"];
    netUnitRevenue: definitions["MonetaryValueModel"];
    grossAccommodationRevenue: definitions["MonetaryValueModel"];
    netAccommodationRevenue: definitions["MonetaryValueModel"];
    grossFoodAndBeveragesRevenue: definitions["MonetaryValueModel"];
    netFoodAndBeveragesRevenue: definitions["MonetaryValueModel"];
    grossOtherRevenue: definitions["MonetaryValueModel"];
    netOtherRevenue: definitions["MonetaryValueModel"];
    grossAdr: definitions["MonetaryValueModel"];
    netAdr: definitions["MonetaryValueModel"];
    revPar: definitions["MonetaryValueModel"];
  };
  PropertyPerformanceReportItemModel: {
    /**
     * Format: date
     * @description The business day
     * @example 2020-10-10
     */
    businessDay: string;
    /**
     * Format: int32
     * @description The number of units physically existing excluding the ones which are out of inventory
     */
    houseCount: number;
    /**
     * Format: int32
     * @description The number of items (e.g. beds, seats, etc.) physically existing excluding the ones which are out of inventory
     */
    houseItemsCount: number;
    /**
     * Format: int32
     * @description The number of sold units plus definitely blocked units from group bookings
     */
    soldCount: number;
    /**
     * Format: int32
     * @description The number of sold items (e.g. beds, seats, etc.) plus definitely blocked items from group bookings
     */
    soldItemsCount: number;
    /**
     * Format: int32
     * @description The number of unsold units: house count minus sold units and out of order units
     */
    unsoldCount: number;
    /**
     * Format: int32
     * @description The number of unsold items (e.g. beds, seats, etc.): house items count minus sold items and out of order items
     */
    unsoldItemsCount: number;
    /**
     * Format: int32
     * @description The number of units which are out of order
     */
    outOfOrderCount: number;
    /**
     * Format: int32
     * @description The number of items (e.g. beds, seats, etc.) which are out of order
     */
    outOfOrderItemsCount: number;
    /**
     * Format: int32
     * @description The number of units which are tentatively blocked
     */
    tentativelyBlockedCount: number;
    /**
     * Format: int32
     * @description The number of items (beds, seats, etc.) which are tentatively blocked
     */
    tentativelyBlockedItemsCount: number;
    /**
     * Format: int32
     * @description The number of arrivals units
     */
    arrivalsCount: number;
    /**
     * Format: int32
     * @description The number of departures units
     */
    departuresCount: number;
    /**
     * Format: int32
     * @description The number of no-show units
     */
    noShowsCount: number;
    /**
     * Format: int32
     * @description The number of cancelled units
     */
    cancellationsCount: number;
    /**
     * Format: double
     * @description The occupancy in percent, which is the ratio of sold units in relation to house count minus out of order units
     */
    occupancyPercentage: number;
    grossUnitRevenue: definitions["MonetaryValueModel"];
    netUnitRevenue: definitions["MonetaryValueModel"];
    grossAccommodationRevenue: definitions["MonetaryValueModel"];
    netAccommodationRevenue: definitions["MonetaryValueModel"];
    grossFoodAndBeveragesRevenue: definitions["MonetaryValueModel"];
    netFoodAndBeveragesRevenue: definitions["MonetaryValueModel"];
    grossOtherRevenue: definitions["MonetaryValueModel"];
    netOtherRevenue: definitions["MonetaryValueModel"];
    grossAdr: definitions["MonetaryValueModel"];
    netAdr: definitions["MonetaryValueModel"];
    revPar: definitions["MonetaryValueModel"];
    /** @description The breakdown per unit group */
    unitGroups: definitions["PropertyPerformancePerUnitGroupModel"][];
  };
  /**
   * @example {
   *   "houseCount": 10,
   *   "houseItemsCount": 0,
   *   "soldCount": 6,
   *   "soldItemsCount": 0,
   *   "unsoldCount": 2,
   *   "unsoldItemsCount": 0,
   *   "outOfOrderCount": 2,
   *   "outOfOrderItemsCount": 0,
   *   "tentativelyBlockedCount": 0,
   *   "tentativelyBlockedItemsCount": 0,
   *   "arrivalsCount": 0,
   *   "departuresCount": 0,
   *   "noShowsCount": 0,
   *   "cancellationsCount": 0,
   *   "occupancyPercentage": 75.00,
   *   "grossUnitRevenue": {
   *     "amount": 830.00,
   *     "currency": "EUR"
   *   },
   *   "netUnitRevenue": {
   *     "amount": 775.70,
   *     "currency": "EUR"
   *   },
   *   "grossAccommodationRevenue": {
   *     "amount": 26.00,
   *     "currency": "EUR"
   *   },
   *   "netAccommodationRevenue": {
   *     "amount": 24.00,
   *     "currency": "EUR"
   *   },
   *   "grossFoodAndBeveragesRevenue": {
   *     "amount": 134.00,
   *     "currency": "EUR"
   *   },
   *   "netFoodAndBeveragesRevenue": {
   *     "amount": 16.00,
   *     "currency": "EUR"
   *   },
   *   "grossOtherRevenue": {
   *     "amount": 194.00,
   *     "currency": "EUR"
   *   },
   *   "netOtherRevenue": {
   *     "amount": 126.00,
   *     "currency": "EUR"
   *   },
   *   "grossAdr": {
   *     "amount": 138.33,
   *     "currency": "EUR"
   *   },
   *   "netAdr": {
   *     "amount": 129.28,
   *     "currency": "EUR"
   *   },
   *   "revPar": {
   *     "amount": 96.96,
   *     "currency": "EUR"
   *   },
   *   "businessDays": [
   *     {
   *       "businessDay": "2024-03-06",
   *       "houseCount": 5,
   *       "houseItemsCount": 0,
   *       "soldCount": 3,
   *       "soldItemsCount": 0,
   *       "unsoldCount": 1,
   *       "unsoldItemsCount": 0,
   *       "outOfOrderCount": 1,
   *       "outOfOrderItemsCount": 0,
   *       "tentativelyBlockedCount": 0,
   *       "tentativelyBlockedItemsCount": 0,
   *       "arrivalsCount": 0,
   *       "departuresCount": 0,
   *       "noShowsCount": 0,
   *       "cancellationsCount": 0,
   *       "occupancyPercentage": 75.0,
   *       "grossUnitRevenue": {
   *         "amount": 350.00,
   *         "currency": "EUR"
   *       },
   *       "netUnitRevenue": {
   *         "amount": 327.10,
   *         "currency": "EUR"
   *       },
   *       "grossAccommodationRevenue": {
   *         "amount": 8.00,
   *         "currency": "EUR"
   *       },
   *       "netAccommodationRevenue": {
   *         "amount": 7.00,
   *         "currency": "EUR"
   *       },
   *       "grossFoodAndBeveragesRevenue": {
   *         "amount": 17.00,
   *         "currency": "EUR"
   *       },
   *       "netFoodAndBeveragesRevenue": {
   *         "amount": 3.00,
   *         "currency": "EUR"
   *       },
   *       "grossOtherRevenue": {
   *         "amount": 47.00,
   *         "currency": "EUR"
   *       },
   *       "netOtherRevenue": {
   *         "amount": 13.00,
   *         "currency": "EUR"
   *       },
   *       "grossAdr": {
   *         "amount": 116.67,
   *         "currency": "EUR"
   *       },
   *       "netAdr": {
   *         "amount": 109.03,
   *         "currency": "EUR"
   *       },
   *       "revPar": {
   *         "amount": 81.78,
   *         "currency": "EUR"
   *       },
   *       "unitGroups": [
   *         {
   *           "unitGroup": {
   *             "id": "MUC-DBL",
   *             "code": "DBL",
   *             "name": "Double",
   *             "description": "Double",
   *             "type": "BedRoom"
   *           },
   *           "houseCount": 4,
   *           "houseItemsCount": 0,
   *           "soldCount": 2,
   *           "soldItemsCount": 0,
   *           "unsoldCount": 1,
   *           "unsoldItemsCount": 0,
   *           "outOfOrderCount": 1,
   *           "outOfOrderItemsCount": 0,
   *           "tentativelyBlockedCount": 0,
   *           "tentativelyBlockedItemsCount": 0,
   *           "arrivalsCount": 0,
   *           "departuresCount": 0,
   *           "noShowsCount": 0,
   *           "cancellationsCount": 0,
   *           "occupancyPercentage": 66.67,
   *           "grossUnitRevenue": {
   *             "amount": 230.00,
   *             "currency": "EUR"
   *           },
   *           "netUnitRevenue": {
   *             "amount": 214.95,
   *             "currency": "EUR"
   *           },
   *           "grossAccommodationRevenue": {
   *             "amount": 4.00,
   *             "currency": "EUR"
   *           },
   *           "netAccommodationRevenue": {
   *             "amount": 3.50,
   *             "currency": "EUR"
   *           },
   *           "grossFoodAndBeveragesRevenue": {
   *             "amount": 8.50,
   *             "currency": "EUR"
   *           },
   *           "netFoodAndBeveragesRevenue": {
   *             "amount": 1.50,
   *             "currency": "EUR"
   *           },
   *           "grossOtherRevenue": {
   *             "amount": 23.50,
   *             "currency": "EUR"
   *           },
   *           "netOtherRevenue": {
   *             "amount": 6.50,
   *             "currency": "EUR"
   *           },
   *           "grossAdr": {
   *             "amount": 115.00,
   *             "currency": "EUR"
   *           },
   *           "netAdr": {
   *             "amount": 107.48,
   *             "currency": "EUR"
   *           },
   *           "revPar": {
   *             "amount": 71.65,
   *             "currency": "EUR"
   *           }
   *         },
   *         {
   *           "unitGroup": {
   *             "id": "MUC-SGL",
   *             "code": "SGL",
   *             "name": "Single",
   *             "description": "Single",
   *             "type": "BedRoom"
   *           },
   *           "houseCount": 1,
   *           "houseItemsCount": 0,
   *           "soldCount": 1,
   *           "soldItemsCount": 0,
   *           "unsoldCount": 0,
   *           "unsoldItemsCount": 0,
   *           "outOfOrderCount": 0,
   *           "outOfOrderItemsCount": 0,
   *           "tentativelyBlockedCount": 0,
   *           "tentativelyBlockedItemsCount": 0,
   *           "arrivalsCount": 0,
   *           "departuresCount": 0,
   *           "noShowsCount": 0,
   *           "cancellationsCount": 0,
   *           "occupancyPercentage": 100.00,
   *           "grossUnitRevenue": {
   *             "amount": 120.00,
   *             "currency": "EUR"
   *           },
   *           "netUnitRevenue": {
   *             "amount": 112.15,
   *             "currency": "EUR"
   *           },
   *           "grossAccommodationRevenue": {
   *             "amount": 4.00,
   *             "currency": "EUR"
   *           },
   *           "netAccommodationRevenue": {
   *             "amount": 3.50,
   *             "currency": "EUR"
   *           },
   *           "grossFoodAndBeveragesRevenue": {
   *             "amount": 8.50,
   *             "currency": "EUR"
   *           },
   *           "netFoodAndBeveragesRevenue": {
   *             "amount": 1.50,
   *             "currency": "EUR"
   *           },
   *           "grossOtherRevenue": {
   *             "amount": 23.50,
   *             "currency": "EUR"
   *           },
   *           "netOtherRevenue": {
   *             "amount": 6.50,
   *             "currency": "EUR"
   *           },
   *           "grossAdr": {
   *             "amount": 120.00,
   *             "currency": "EUR"
   *           },
   *           "netAdr": {
   *             "amount": 112.15,
   *             "currency": "EUR"
   *           },
   *           "revPar": {
   *             "amount": 112.15,
   *             "currency": "EUR"
   *           }
   *         }
   *       ]
   *     },
   *     {
   *       "businessDay": "2024-03-07",
   *       "houseCount": 5,
   *       "houseItemsCount": 0,
   *       "soldCount": 3,
   *       "soldItemsCount": 0,
   *       "unsoldCount": 1,
   *       "unsoldItemsCount": 0,
   *       "outOfOrderCount": 1,
   *       "outOfOrderItemsCount": 0,
   *       "tentativelyBlockedCount": 0,
   *       "tentativelyBlockedItemsCount": 0,
   *       "arrivalsCount": 0,
   *       "departuresCount": 0,
   *       "noShowsCount": 0,
   *       "cancellationsCount": 0,
   *       "occupancyPercentage": 75.00,
   *       "grossUnitRevenue": {
   *         "amount": 480.00,
   *         "currency": "EUR"
   *       },
   *       "netUnitRevenue": {
   *         "amount": 448.60,
   *         "currency": "EUR"
   *       },
   *       "grossAccommodationRevenue": {
   *         "amount": 18.00,
   *         "currency": "EUR"
   *       },
   *       "netAccommodationRevenue": {
   *         "amount": 17.00,
   *         "currency": "EUR"
   *       },
   *       "grossFoodAndBeveragesRevenue": {
   *         "amount": 117.00,
   *         "currency": "EUR"
   *       },
   *       "netFoodAndBeveragesRevenue": {
   *         "amount": 13.00,
   *         "currency": "EUR"
   *       },
   *       "grossOtherRevenue": {
   *         "amount": 147.00,
   *         "currency": "EUR"
   *       },
   *       "netOtherRevenue": {
   *         "amount": 113.00,
   *         "currency": "EUR"
   *       },
   *       "grossAdr": {
   *         "amount": 160.00,
   *         "currency": "EUR"
   *       },
   *       "netAdr": {
   *         "amount": 149.53,
   *         "currency": "EUR"
   *       },
   *       "revPar": {
   *         "amount": 112.15,
   *         "currency": "EUR"
   *       },
   *       "unitGroups": [
   *         {
   *           "unitGroup": {
   *             "id": "MUC-DBL",
   *             "code": "DBL",
   *             "name": "Double",
   *             "description": "Double",
   *             "type": "BedRoom"
   *           },
   *           "houseCount": 4,
   *           "houseItemsCount": 0,
   *           "soldCount": 3,
   *           "soldItemsCount": 0,
   *           "unsoldCount": 0,
   *           "unsoldItemsCount": 0,
   *           "outOfOrderCount": 1,
   *           "outOfOrderItemsCount": 0,
   *           "tentativelyBlockedCount": 0,
   *           "tentativelyBlockedItemsCount": 0,
   *           "arrivalsCount": 0,
   *           "departuresCount": 0,
   *           "noShowsCount": 0,
   *           "cancellationsCount": 0,
   *           "occupancyPercentage": 100.00,
   *           "grossUnitRevenue": {
   *             "amount": 370.00,
   *             "currency": "EUR"
   *           },
   *           "netUnitRevenue": {
   *             "amount": 345.79,
   *             "currency": "EUR"
   *           },
   *           "grossAccommodationRevenue": {
   *             "amount": 9.00,
   *             "currency": "EUR"
   *           },
   *           "netAccommodationRevenue": {
   *             "amount": 8.50,
   *             "currency": "EUR"
   *           },
   *           "grossFoodAndBeveragesRevenue": {
   *             "amount": 56.50,
   *             "currency": "EUR"
   *           },
   *           "netFoodAndBeveragesRevenue": {
   *             "amount": 7.50,
   *             "currency": "EUR"
   *           },
   *           "grossOtherRevenue": {
   *             "amount": 73.50,
   *             "currency": "EUR"
   *           },
   *           "netOtherRevenue": {
   *             "amount": 56.50,
   *             "currency": "EUR"
   *           },
   *           "grossAdr": {
   *             "amount": 123.33,
   *             "currency": "EUR"
   *           },
   *           "netAdr": {
   *             "amount": 115.26,
   *             "currency": "EUR"
   *           },
   *           "revPar": {
   *             "amount": 215.26,
   *             "currency": "EUR"
   *           }
   *         },
   *         {
   *           "unitGroup": {
   *             "id": "MUC-SGL",
   *             "code": "SGL",
   *             "name": "Single",
   *             "description": "Single",
   *             "type": "BedRoom"
   *           },
   *           "houseCount": 1,
   *           "houseItemsCount": 0,
   *           "soldCount": 1,
   *           "soldItemsCount": 0,
   *           "unsoldCount": 0,
   *           "unsoldItemsCount": 0,
   *           "outOfOrderCount": 0,
   *           "outOfOrderItemsCount": 0,
   *           "tentativelyBlockedCount": 0,
   *           "tentativelyBlockedItemsCount": 0,
   *           "arrivalsCount": 0,
   *           "departuresCount": 0,
   *           "noShowsCount": 0,
   *           "cancellationsCount": 0,
   *           "occupancyPercentage": 100.00,
   *           "grossUnitRevenue": {
   *             "amount": 110.00,
   *             "currency": "EUR"
   *           },
   *           "netUnitRevenue": {
   *             "amount": 102.80,
   *             "currency": "EUR"
   *           },
   *           "grossAccommodationRevenue": {
   *             "amount": 9.00,
   *             "currency": "EUR"
   *           },
   *           "netAccommodationRevenue": {
   *             "amount": 8.50,
   *             "currency": "EUR"
   *           },
   *           "grossFoodAndBeveragesRevenue": {
   *             "amount": 56.50,
   *             "currency": "EUR"
   *           },
   *           "netFoodAndBeveragesRevenue": {
   *             "amount": 7.50,
   *             "currency": "EUR"
   *           },
   *           "grossOtherRevenue": {
   *             "amount": 73.50,
   *             "currency": "EUR"
   *           },
   *           "netOtherRevenue": {
   *             "amount": 56.50,
   *             "currency": "EUR"
   *           },
   *           "grossAdr": {
   *             "amount": 110.00,
   *             "currency": "EUR"
   *           },
   *           "netAdr": {
   *             "amount": 102.80,
   *             "currency": "EUR"
   *           },
   *           "revPar": {
   *             "amount": 102.80,
   *             "currency": "EUR"
   *           }
   *         }
   *       ]
   *     }
   *   ]
   * }
   */
  PropertyPerformanceReportModel: {
    /**
     * Format: int32
     * @description The number of units physically existing excluding the ones which are out of inventory
     */
    houseCount: number;
    /**
     * Format: int32
     * @description The number of items (e.g. beds, seats, etc.) physically existing excluding the ones which are out of inventory
     */
    houseItemsCount: number;
    /**
     * Format: int32
     * @description The number of sold units plus definitely blocked units from group bookings
     */
    soldCount: number;
    /**
     * Format: int32
     * @description The number of sold items (e.g. beds, seats, etc.) plus definitely blocked items from group bookings
     */
    soldItemsCount: number;
    /**
     * Format: int32
     * @description The number of unsold units: house count minus sold units and out of order units
     */
    unsoldCount: number;
    /**
     * Format: int32
     * @description The number of unsold items (e.g. beds, seats, etc.): house items count minus sold items and out of order items
     */
    unsoldItemsCount: number;
    /**
     * Format: int32
     * @description The number of units which are out of order
     */
    outOfOrderCount: number;
    /**
     * Format: int32
     * @description The number of items (e.g. beds, seats, etc.) which are out of order
     */
    outOfOrderItemsCount: number;
    /**
     * Format: int32
     * @description The number of units which are tentatively blocked
     */
    tentativelyBlockedCount: number;
    /**
     * Format: int32
     * @description The number of items (beds, seats, etc.) which are tentatively blocked
     */
    tentativelyBlockedItemsCount: number;
    /**
     * Format: int32
     * @description The number of arrivals units
     */
    arrivalsCount: number;
    /**
     * Format: int32
     * @description The number of departures units
     */
    departuresCount: number;
    /**
     * Format: int32
     * @description The number of no-show units
     */
    noShowsCount: number;
    /**
     * Format: int32
     * @description The number of cancelled units
     */
    cancellationsCount: number;
    /**
     * Format: double
     * @description The occupancy in percent, which is the ratio of sold units in relation to house count minus out of order units
     */
    occupancyPercentage: number;
    grossUnitRevenue: definitions["MonetaryValueModel"];
    netUnitRevenue: definitions["MonetaryValueModel"];
    grossAccommodationRevenue: definitions["MonetaryValueModel"];
    netAccommodationRevenue: definitions["MonetaryValueModel"];
    grossFoodAndBeveragesRevenue: definitions["MonetaryValueModel"];
    netFoodAndBeveragesRevenue: definitions["MonetaryValueModel"];
    grossOtherRevenue: definitions["MonetaryValueModel"];
    netOtherRevenue: definitions["MonetaryValueModel"];
    grossAdr: definitions["MonetaryValueModel"];
    netAdr: definitions["MonetaryValueModel"];
    revPar: definitions["MonetaryValueModel"];
    /** @description The breakdown by business day for the specified filter criteria */
    businessDays?: definitions["PropertyPerformanceReportItemModel"][];
  };
  ReceiptModel: {
    /** @description The type of receipt. */
    type?: "Custom" | "Reservation" | "Invoice" | "PspReference";
    /** @description The receipt number. */
    number: string;
  };
  /**
   * @example {
   *   "account": {
   *     "name": "Revenues",
   *     "number": "5000",
   *     "type": "Revenues"
   *   },
   *   "netAmount": {
   *     "amount": 8000.0,
   *     "currency": "EUR"
   *   },
   *   "grossAmount": {
   *     "amount": 10000.0,
   *     "currency": "EUR"
   *   },
   *   "children": [
   *     {
   *       "account": {
   *         "name": "Revenues Accommodation",
   *         "number": "RevenueAccommodation",
   *         "type": "Revenues"
   *       },
   *       "netAmount": {
   *         "amount": 5000.0,
   *         "currency": "EUR"
   *       },
   *       "grossAmount": {
   *         "amount": 6000.0,
   *         "currency": "EUR"
   *       },
   *       "children": [
   *         {
   *           "account": {
   *             "name": "Revenues Accommodation (7%)",
   *             "number": "RevenuesAccommodation_Reduced",
   *             "type": "Revenues"
   *           },
   *           "netAmount": {
   *             "amount": 5000.0,
   *             "currency": "EUR"
   *           },
   *           "grossAmount": {
   *             "amount": 6000.0,
   *             "currency": "EUR"
   *           }
   *         }
   *       ]
   *     },
   *     {
   *       "account": {
   *         "name": "Revenues F&B",
   *         "number": "RevenueFoodAndBeverages",
   *         "type": "Revenues"
   *       },
   *       "netAmount": {
   *         "amount": 3000.0,
   *         "currency": "EUR"
   *       },
   *       "grossAmount": {
   *         "amount": 4000.0,
   *         "currency": "EUR"
   *       }
   *     }
   *   ]
   * }
   */
  RevenuesReportItemModel: {
    account: definitions["ExportAccountModel"];
    netAmount: definitions["MonetaryValueModel"];
    grossAmount: definitions["MonetaryValueModel"];
    /** @description Child accounts of this account */
    children?: definitions["RevenuesReportItemModel"][];
  };
  RoomNightsConsumedModel: {
    /**
     * Format: int64
     * @description Room nights consumed.
     */
    roomNightsConsumed: number;
  };
  TaxAmountModel: {
    /** @description The VAT type */
    type:
      | "Null"
      | "VeryReduced"
      | "Reduced"
      | "Normal"
      | "Without"
      | "Special"
      | "ReducedCovid19"
      | "NormalCovid19";
    /**
     * Format: double
     * @description The currently valid percent to calculate the VAT
     */
    percent: number;
    /**
     * Format: double
     * @description The tax amount
     */
    amount: number;
  };
  TaxDetailModel: {
    vatType:
      | "Null"
      | "VeryReduced"
      | "Reduced"
      | "Normal"
      | "Without"
      | "Special"
      | "ReducedCovid19"
      | "NormalCovid19";
    /** Format: double */
    vatPercent: number;
    net: definitions["MonetaryValueModel"];
    tax: definitions["MonetaryValueModel"];
  };
  TransactionsGrossExportListItemModel: {
    reservation?: definitions["TransactionsGrossExportReservationModel"];
    /**
     * Format: date-time
     * @description Timestamp with time zone information, when the booking was done<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>
     */
    timestamp: string;
    /**
     * Format: date
     * @description The business date when the booking was done
     * @example 2020-10-10
     */
    date: string;
    debitedAccount: definitions["ExportAccountModel"];
    creditedAccount: definitions["ExportAccountModel"];
    /** @description The type of business transaction which triggered the booking */
    command:
      | "PostCharge"
      | "PostPayment"
      | "MoveLineItem"
      | "PostPrepayment"
      | "PostToAccountsReceivables"
      | "PostPrepaymentVat"
      | "PostToLossOfAccountsReceivables"
      | "System";
    /** @description The currency of the transaction */
    currency: string;
    /**
     * Format: double
     * @description The gross amount being booked
     */
    grossAmount: number;
    /**
     * Format: double
     * @description The net amount being booked
     */
    netAmount: number;
    /** @description The taxes which make up the difference between net and gross amount */
    taxes?: definitions["TaxAmountModel"][];
    receipt: definitions["ReceiptModel"];
    /** @description The original raw transaction entry number which got converted to these one or 2 lines. */
    sourceEntryNumber: string;
    /** @description The reference for the transactions, reservation id for guest folios, booking id for booking folio, folio id for external folios, property code for the house folio */
    reference: string;
    /** @description Does this transaction belong to a reservation, a house or an external folio */
    referenceType: "House" | "Guest" | "External" | "Booking";
  };
  /**
   * @example {
   *   "transactions": [
   *     {
   *       "reservation": {
   *         "id": "QPMZZTUK-1",
   *         "status": "CheckedOut",
   *         "arrival": "2020-10-10T11:11:00Z",
   *         "departure": "2020-10-12T11:11:00Z"
   *       },
   *       "timestamp": "2024-03-12T09:20:29.9007222Z",
   *       "date": "2024-03-06",
   *       "debitedAccount": {
   *         "name": "Cash Payment",
   *         "number": "1600",
   *         "type": "Revenues"
   *       },
   *       "creditedAccount": {
   *         "name": "Receivables for Reservation QPMZZTUK-1",
   *         "number": "QPMZZTUK-1_Receivables",
   *         "type": "Revenues"
   *       },
   *       "command": "PostCharge",
   *       "currency": "EUR",
   *       "grossAmount": 100.0,
   *       "netAmount": 100.0,
   *       "receipt": {
   *         "type": "Reservation",
   *         "number": "QPMZZTUK-1-V3"
   *       },
   *       "sourceEntryNumber": "SourceEntryNumber",
   *       "reference": "REFERENCE",
   *       "referenceType": "Guest"
   *     },
   *     {
   *       "timestamp": "2024-03-12T09:20:29.9007396Z",
   *       "date": "2024-03-06",
   *       "debitedAccount": {
   *         "name": "Revenues Accommodation",
   *         "number": "5001",
   *         "type": "Revenues"
   *       },
   *       "creditedAccount": {
   *         "name": "House Account",
   *         "number": "HOUSE_HCF",
   *         "type": "Revenues"
   *       },
   *       "command": "PostCharge",
   *       "currency": "EUR",
   *       "grossAmount": 214.0,
   *       "netAmount": 200.0,
   *       "taxes": [
   *         {
   *           "type": "Reduced",
   *           "percent": 7.0,
   *           "amount": 14.0
   *         }
   *       ],
   *       "receipt": {
   *         "type": "Reservation",
   *         "number": "QPMZZTUK-1-V3"
   *       },
   *       "sourceEntryNumber": "SourceEntryNumber",
   *       "reference": "REFERENCE",
   *       "referenceType": "House"
   *     }
   *   ],
   *   "count": 2
   * }
   */
  TransactionsGrossExportListModel: {
    /** @description The list of gross transactions with additional metadata */
    transactions: definitions["TransactionsGrossExportListItemModel"][];
    /**
     * Format: int64
     * @description Total count of items
     */
    count: number;
  };
  TransactionsGrossExportReservationModel: {
    /** @description Reservation id */
    id: string;
    /** @description Status of the reservation */
    status: "Confirmed" | "InHouse" | "CheckedOut" | "Canceled" | "NoShow";
    /**
     * Format: date-time
     * @description Date of arrival<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>
     */
    arrival: string;
    /**
     * Format: date-time
     * @description Date of departure<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>
     */
    departure: string;
  };
  TravelPurposeEntry: {
    purpose?: "Business" | "Leisure";
    /** Format: int32 */
    number: number;
    /** Format: double */
    percent: number;
    reservationIds?: string[];
  };
}

export interface operations {
  /** Returns a list of gross transactions with metadata (folio and reservation details).<br>You must have this scope: 'reports.read'. */
  "ReportsReportsGross-transactionsPost": {
    parameters: {
      query: {
        /** Specifies the property transactions will be filtered by. */
        propertyId: string;
        /** Filter by business date<br />You can provide an array of string expressions which all need to apply.<br />Each expression has the form of 'OPERATION_VALUE' where VALUE needs to be of the valid format of the property type and OPERATION can be:<br />'eq' for equals<br />'neq' for not equals<br />'lt' for less than<br />'gt' for greater than<br />'lte' for less than or equals<br />'gte' for greater than or equals<br />For instance<br />'eq_5' would mean the value should equal 5<br />'lte_7' would mean the value should be less than or equal to 7 */
        dateFilter: string[];
        /** Filter transactions by reference (reservation id/booking id/external folio id/property id for house folio). */
        reference?: string;
      };
      header: {
        /**
         * Unique key for safely retrying requests without accidentally performing the same operation twice.
         * We'll always send back the same response for requests made with the same key,
         * and keys can't be reused with different request parameters. Keys expire after 24 hours.
         */
        "Idempotency-Key"?: string;
      };
    };
    responses: {
      200: {
        schema: definitions["TransactionsGrossExportListModel"];
      };
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Returns a list of ordered services per day with information about the guest and the reservation this service was ordered for.<br>You must have this scope: 'reports.read'. */
  "ReportsReportsOrdered-servicesGet": {
    parameters: {
      query: {
        /** Property Id */
        propertyId: string;
        /** Service ids the report should be generated for */
        serviceIds: string[];
        /** The inclusive start date of the interval. */
        from: string;
        /** The exclusive end date of the interval. */
        to: string;
      };
    };
    responses: {
      200: {
        schema: definitions["OrderedServicesListModel"];
      };
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /**
   * Returns room nights for a property for a certain month. Only over-night rateplans are considered.
   * <br />
   * DEPRECATED: will be replaced by "/room-nights"<br>You must have this scope: 'reports.read'.
   */
  "ReportsReportsRoom-nights-consumedGet": {
    parameters: {
      query: {
        /** Requested property. */
        propertyId: string;
        /** Requested month for the report. */
        month: number;
        /** Requested year for the report. */
        year: number;
      };
    };
    responses: {
      200: {
        schema: definitions["RoomNightsConsumedModel"];
      };
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /**
   * Returns room nights for a property for a certain month. Only over-night rateplans are considered.<br />
   * Includes statistical information on purpose of travel, and nationality.
   * The status considered are: in-house, confirmed, and checked out.<br>You must have this scope: 'reports.read'.
   */
  "ReportsReportsRoom-nightsGet": {
    parameters: {
      query: {
        /** Requested property. */
        propertyId: string;
        /** Requested month for the report. */
        month: number;
        /** Requested year for the report. */
        year: number;
      };
    };
    responses: {
      200: {
        schema: definitions["GuestReportModel"];
      };
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /**
   * Returns bed nights for a property for a certain month. Only over-night rateplans are considered.<br />
   * Counts number of guests.
   * Includes statistical information on purpose of travel, and nationality. The data is taken from the primary guest only.
   * The status considered are: in-house, confirmed, and checked out.<br>You must have this scope: 'reports.read'.
   */
  "ReportsReportsBed-nightsGet": {
    parameters: {
      query: {
        /** Requested property. */
        propertyId: string;
        /** Requested month for the report. */
        month: number;
        /** Requested year for the report. */
        year: number;
      };
    };
    responses: {
      200: {
        schema: definitions["GuestReportModel"];
      };
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /**
   * Returns number of arriving guests for a property for a certain month. Only over-night rateplans are considered.<br />
   * Includes statistical information on purpose of travel, and nationality. The data is taken from the primary guest only.
   * The status considered are: in-house, confirmed, and checked out.<br>You must have this scope: 'reports.read'.
   */
  ReportsReportsArrivalsGet: {
    parameters: {
      query: {
        /** Requested property. */
        propertyId: string;
        /** Requested month for the report. */
        month: number;
        /** Requested year for the report. */
        year: number;
      };
    };
    responses: {
      200: {
        schema: definitions["GuestReportModel"];
      };
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /**
   * The property performance API return you key performance indicator for the selected property like occupancy, ADR and RevPAR.
   * It only considers the originally booked amounts for sold units excluding any additional services or manually posted charges
   * or allowances. The results can be filterd to only show you data for a certain part of the business. For example you can exclude
   * day-use reservations or complimentary rate plans.<br>You must have this scope: 'reports.read'.
   */
  "ReportsReportsProperty-performanceGet": {
    parameters: {
      query: {
        /** The ID of the property */
        propertyId: string;
        /** The inclusive start date of the interval */
        from: string;
        /** The inclusive end date of the interval */
        to: string;
        /** The company IDs used to filter the retrieved data */
        companyIds?: string[];
        /** The rate plan IDs used to filter the retrieved data */
        ratePlanIds?: string[];
        /** The unit group types used to filter the retrieved data */
        unitGroupTypes?: (
          | "BedRoom"
          | "MeetingRoom"
          | "EventSpace"
          | "ParkingLot"
          | "Other"
        )[];
        /** The unit group IDs used to filter the retrieved data */
        unitGroupIds?: string[];
        /** The time slice definition IDs used to filter the retrieved data */
        timeSliceDefinitionIds?: string[];
        /** The channel codes used to filter the retrieved data */
        channelCodes?: (
          | "Direct"
          | "BookingCom"
          | "Ibe"
          | "ChannelManager"
          | "Expedia"
          | "Homelike"
          | "Hrs"
          | "AltoVita"
          | "DesVu"
        )[];
        /** The market segment IDs used to filter the retrieved data */
        marketSegmentIds?: string[];
        /** The travel purpose to filter the retrieved data */
        travelPurpose?: "Business" | "Leisure";
        /** List of all embedded resources that should be expanded in the response. Possible values are: businessDays. All other values will be silently ignored. */
        expand?: "businessDays"[];
      };
    };
    responses: {
      200: {
        schema: definitions["PropertyPerformanceReportModel"];
      };
      /** No Content */
      204: never;
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** <br>You must have this scope: 'reports.read'. */
  "ReportsReportsCompany-invoices-vatGet": {
    parameters: {
      query: {
        /** Property ID */
        propertyId: string;
        /** Company IDs the report should be generated for */
        companyIds?: string[];
        /** Set a date interval to get the report for. Cannot be more than 1 month.<br />You can provide an array of string expressions which all need to apply.<br />Each expression has the form of 'OPERATION_VALUE' where VALUE needs to be of the valid format of the property type and OPERATION can be:<br />'eq' for equals<br />'neq' for not equals<br />'lt' for less than<br />'gt' for greater than<br />'lte' for less than or equals<br />'gte' for greater than or equals<br />For instance<br />'eq_5' would mean the value should equal 5<br />'lte_7' would mean the value should be less than or equal to 7 */
        dateFilter?: string[];
      };
    };
    responses: {
      200: {
        schema: definitions["CompaniesVatReportListModel"];
      };
      /** No Content */
      204: never;
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** <br>You must have this scope: 'reports.read'. */
  ReportsReportsRevenuesGet: {
    parameters: {
      query: {
        /** Property ID */
        propertyId: string;
        /** The inclusive start date of the interval. */
        from: string;
        /** The exclusive end date of the interval. The interval is limited to one year. */
        to: string;
        /** The language for the the report */
        languageCode?: string;
      };
    };
    responses: {
      200: {
        schema: definitions["RevenuesReportItemModel"];
      };
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
}

export interface external {}
